# Generated by Django 2.2.2 on 2019-06-26 06:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Resource type',
                'verbose_name_plural': 'Resource types',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Name')),
                ('localization', models.CharField(max_length=256, verbose_name='localization')),
                ('capacity', models.PositiveSmallIntegerField(default=1, verbose_name='capacity')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.ResourceType')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='From')),
                ('to_date_time', models.DateTimeField(verbose_name='To')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.Resource')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
